### ISSUE TITLE
Searching for a string whilst wildcards

### ISSUE THREAD

**Issue by mbuk** [babenkoivan/elastic-scout-driver-plus#92] opened 2021-10-13 16:10 UTC
This isn't a bug more of a question

| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.4.19
| Elasticsearch            | 6.8.0
| Laravel                      | 8.40
| Laravel Scout           | ^9.1
| Elastic Scout Driver |^1.4

**Describe the bug** (it's not a but)
We've setup a mapping
```
'properties' => [
            'title' => [
                'type' => 'text',
                // Also you can configure multi-fields, more details you can find here https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html
                'fields' => [
                    'raw' => [
                        'type' => 'text',
                    ]
                ]
            ]
]
```

We've imported the data and we're searching using: 
```
  $ret = Page::wildcardSearch()
                        ->field('title')
                        ->value('*' . mb_strtolower(urldecode($request->get('string'))) . '*')
                        ->highlight('title', [])
                        ->execute();
```

If we search a string of "month" we get a result
If I search for a string of "a" we get a result
If I search for "a month" (the document contains "a month") I don't get a result.

**This is clearly a misuse issue** Can you point me in the direction of what I'm doing wrong?

**To Reproduce**
N/A

**Current behavior**
N/A

**Expected behavior**
N/A

**Comment by babenkoivan** [comment] 2021-11-01 18:02
Hi @mbuk, I'm afraid there can be dozens of reasons why you don't get a result (e.g. two spaces between the terms or maybe a tab). I'd suggest using a more appropriate query type for full-text search, for example, `match` or even a `query string`.

I'm closing this one cause it's not a bug, but rather an Elasticsearch related question 🙂

**Closed by babenkoivan** 2021-11-01 18:02 UTC
Labels: bug

**Comment by mbuk** [comment] 2021-11-01 18:03
No worries we figured it out with a bunch of trial and error - sorry I meant to close this but never got around to it
