### ISSUE TITLE
Elasticsearch aliases break models()

### ISSUE THREAD

**Issue by spiritinlife** [babenkoivan/elastic-scout-driver-plus#38] opened 2020-12-03 11:24 UTC
| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.2.5
| Elasticsearch            | 7.7
| Laravel                      | 7.0.0
| Laravel Scout           | 8.4
| Elastic Scout Driver | 1.2

**Describe the bug**
When using alias of an index, `models()` doesn't bring anything from db. 

**To Reproduce**
Create an alias for an index.
Use this alias as searchableAs.
Execute a query and fetch models.
You will see their empty.

**Current behavior**
We are getting no models back.

**Expected behavior**
We should be getting models back.

I believe this is an issue with how this library maps models to indexes with searchableAs.
Elasticsearch will return the actual indexName and not the alias thus breaking the lookup in the models map.

**Comment by babenkoivan** [comment] 2020-12-04 17:45
Noted, this definitely looks like a bug

**Comment by kamilkozak** [comment] 2020-12-05 12:04
@spiritinlife I tested it because I want to use this library in my project and I can't reproduce this bug. Are you sure the problem is not on your side?

**Comment by spiritinlife** [comment] 2020-12-05 16:08
@kamilkozak steps to reproduce.

1. create an index e.g. named `production1`
2. create an alias of this index e.g. named `production`
3. use `production` as the index name passed in your `searchableAs` method.
4. do a query and try to get the models with the `models` function.

What u will see is that no models are returned.
If you check the SearchResult you will find matches and if you look into a match you will see that the indexName is `production` and not `production1`.

So because a Match->model function calls makeByIndexNameAndDocumentId in LazyModelFactory which finds the model class by its indexName, it fails to do so.d

Did you perform these steps?

**Comment by babenkoivan** [comment] 2021-01-05 12:06
Hey @spiritinlife, the issue is fixed in the latest [v1.15.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.15.0) release. Please verify if it works for you. If there are any troubles, you can reopen the issue.

**Closed by babenkoivan** 2021-01-05 12:06 UTC
Labels: bug
