### ISSUE TITLE
search email [Help]

### ISSUE THREAD

**Issue by RolandVerner** [babenkoivan/elastic-scout-driver-plus#73] opened 2021-06-29 11:20 UTC
Sorry, I can't find any information about it maybe somebody can help.

```
    $search = User::boolsearch();
        $search->should((new MatchQueryBuilder())->field('email')->query($this->search)->fuzziness('AUTO'));
        $search->minimumShouldMatch(1);
        $search->withTrashed();
    $users = $search->paginate($this->pagination);
    $users->setCollection($users->models());
```

it's not searching without I not write a full email
- rolandverner will not find
- rolandverner@ will not find 
- rolandverner@outlook will not find 
and rolandverner@outlook.com find correctly with fuzziness the similar finds

---------------------------------------------------------------------------------------------------------------------------------
And another question how to use eloquent with eslaticsearch?
```
        $users = User::query();
        $users->accountVerified();
        $users->registered();

        $users->boolsearch();
        $search->should((new MatchQueryBuilder())->field('email')->query($this->search)->fuzziness('AUTO'));
        $search->minimumShouldMatch(1);
        $search->withTrashed();
```

**Comment by babenkoivan** [comment] 2021-07-06 07:05
> it's not searching without I not write a full email

Please check your mapping, not all types allow partial search.

> And another question how to use eloquent with eslaticsearch?

The driver searches data in Elasticsearch, then finds the respective models in the database using primary keys. This is how Scout works in general. If you need to refine the search results, it's better to add a filter in the search request itself.

**Comment by babenkoivan** [comment] 2021-07-06 07:06
Closing as it's not a bug or a feature request.

**Closed by babenkoivan** 2021-07-06 07:06 UTC
